branches:
  only:
    - master
    
install:
  - cd c:/QT
  - dir
  - set QTDIR=C:\Qt\5.9.3\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  
build_script:
  - cd C:\projects\pangaea
  - qmake src.pro
  - mingw32-make
  
after_build:
  - git clone https://github.com/siborion/pangaea_flat.git release/flat
  - windeployqt.exe release/PangaeaCPPA.exe --release --qmldir release/flat 
  - rm release/*.o
  - rm release/*.cpp
  - ISCC inno.iss

artifacts:
  - path: distrib
    type: zip
