
#branches:
#  only:
#    - master

    
install:
  - cd c:/QT
  - set QTDIR=C:\Qt\5.9.3\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  
build_script:
  - cd C:\Qt\5.9.3\mingw53_32
  - dir
  - cd C:\projects\pangaea
  - qmake src.pro
  - mingw32-make
  
after_build:
  - git clone https://github.com/siborion/pangaea_flat.git release/flat
  - windeployqt.exe release/PangaeaCPPA.exe --release --qmldir release/flat --verbose 0
  - rm release/*.o
  - rm release/*.cpp
  - ISCC inno.iss /dJenkinsAppVersion=%APPVEYOR_BUILD_VERSION%

artifacts:
  - path: distrib
    type: zip

deploy:
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    provider: GitHub
    auth_token:
        secure: viysZ6KstlTiK6Jq6vKwhp6N9rbcM78R83yPOZbVmush/P3EwYs/Sk9f1HWtiUrn
    force_update: true
    on:
        appveyor_repo_tag: true   
