
branches:
  only:
    - master
    
install:
  - cd c:/QT
  - set QTDIR=C:\Qt\5.9.3\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  
build_script:
  - cd C:\projects\pangaea
  - qmake src.pro
  - mingw32-make
  
after_build:
  - git clone https://github.com/siborion/pangaea_flat.git release/flat
#  - windeployqt.exe release/PangaeaCPPA.exe --release --qmldir release/flat --verbose 0
  - rm release/*.o
  - rm release/*.cpp
  - ISCC inno.iss /dJenkinsAppVersion=%APPVEYOR_BUILD_VERSION%

artifacts:
  - path: distrib
    type: zip

deploy:
  provider: GitHub
  description: 'Release description'
  force_update: true
  auth_token:
  secure: WNGO0uMfLGWtgW7fEn7J7JcXoYYG4Jgv0bvmxAwmG3Vmw72ZK18YVeM6V8rYN1GbgVkeLwPNSFKUVPdirmnj0TcY9R2BSrHJSBEbuPMTmxijl52zJh1jb2FQpLGYKXGmyVDiO6tu9Wxhhd4MnbXC7PVUGLB1A3kfavFdFD371qzz3UPBlJkyRKT+/6FaV4BmsHx1vN5KsE62MqNsYufGU+UIjMv8uo8oT+jkCJHZmXacsJkxmZIQcEuaiQ3XAA0vy87F/ikN7/QsNWTQwoINRoCU5soy+9DJ6/WaPJUI0KpPiveXKIyYB0SgDOgwgcOs1CNIQISWjlVqTrwl8j9bT0KdD7gfIQMhvniTFkcjbbCui7nDwnkrlFl9uYvXE09uNBhe4CG6fn6LHWzIQn7osojT3jBc9uW6cOd9Ls/K7uQVj1nzbf6wKkuAkOsUU8jIXjgNclvT/wRj0nzrm0DvC81Sk8d81n0EdyGHqGPCYYPYNOqqpviKyXK71xLVeG8M2PJWwYGNOChrwmU5oFSj9A==
  artifact: /.*\.zip/            # upload all NuGet packages to release assets
  appveyor_repo_tag: true        # deploy on tag push only  
  on:
    branch: master                 # release from master branch only
 
